#!/usr/bin/env python3
"""
bake_anim.py — FaceFormer/VOCA output -> anim_data.js for conduit

Takes a speech-driven animation .npy on FLAME topology (shape (T, 15069)
or (T, 5023, 3), as produced by FaceFormer's demo.py with the vocaset
model) and bakes it into a quantized playback file for index.html.

Per-frame motion is taken as deltas vs frame 0, so the model's subject
template doesn't need to match our head — only the topology does.
Deltas are remapped through origIdx (the original-FLAME index of every
vertex in our stripped/seam-fixed mesh), scaled by the same scene
transform as head_data.js, and quantized to int16.

Usage:
  python3 tools/bake_anim.py prediction.npy --fps 30 --wav speech.wav
Outputs anim_data.js next to index.html. Add to the page with:
  <script src="anim_data.js"></script>   (after head_data.js)
Then press [SPACE] in the page to play.
"""
import argparse
import base64
import json

import numpy as np

FLAME_VERTS = 5023


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('npy', help='(T,15069) or (T,5023,3) vertex frames')
    ap.add_argument('--fps', type=int, default=30,
                    help='frame rate of the prediction (vocaset demo: 30)')
    ap.add_argument('--wav', default=None,
                    help='audio file name to play alongside (optional; '
                         'place the wav next to index.html)')
    ap.add_argument('--min-move', type=float, default=0.3,
                    help='drop verts whose peak motion is below this (mm)')
    ap.add_argument('--head', default='head_data.js')
    ap.add_argument('--out', default='anim_data.js')
    args = ap.parse_args()

    frames = np.load(args.npy)
    if frames.ndim == 2:
        assert frames.shape[1] == FLAME_VERTS * 3, frames.shape
        frames = frames.reshape(len(frames), FLAME_VERTS, 3)
    assert frames.shape[1:] == (FLAME_VERTS, 3), frames.shape
    T = len(frames)

    js = open(args.head).read()
    head = json.loads(js[js.index('{'):js.rindex(';')])
    orig_idx = np.frombuffer(base64.b64decode(head['origIdx']), np.uint16)
    scale = head['xform']['scale']

    # motion = delta vs first frame, remapped to our mesh, scene-scaled
    deltas = (frames - frames[0])[:, orig_idx, :] * scale   # (T, n, 3)

    # sparse: drop verts whose motion never exceeds --min-move (mm).
    # Speech models micro-jitter every vertex; the sub-threshold tail is
    # invisible (<1px at typical view size) but dominates file size.
    thresh_scene = args.min_move / 1000.0 * scale
    mover = (np.linalg.norm(deltas, axis=2).max(axis=0) > thresh_scene)
    sparse_idx = np.where(mover)[0].astype(np.uint16)
    deltas = deltas[:, mover, :]                            # (T, nS, 3)
    print(f"sparse: {mover.sum()}/{len(mover)} verts kept "
          f"(> {args.min_move} mm peak motion)")

    peak = float(np.abs(deltas).max()) if deltas.size else 0.0
    qscale = peak / 32767.0 if peak > 0 else 1.0
    q = np.round(deltas / qscale).astype(np.int16)

    payload = {
        'frames': T,
        'fps': args.fps,
        'scale': qscale,
        'wav': args.wav,
        'sparseIdx': base64.b64encode(
            np.ascontiguousarray(sparse_idx).tobytes()).decode(),
        'data': base64.b64encode(np.ascontiguousarray(q).tobytes()).decode(),
        'meta': {'source': args.npy, 'peak_displacement': round(peak, 5),
                 'min_move_mm': args.min_move},
    }
    out = ('// generated by tools/bake_anim.py — do not edit\n'
           'const ANIM_DATA = ' + json.dumps(payload) + ';\n')
    with open(args.out, 'w') as f:
        f.write(out)
    print(f"{args.out}: {T} frames @ {args.fps}fps, "
          f"{len(sparse_idx)} sparse verts, peak {peak:.4f} scene units, "
          f"{len(out)/1024:.0f} KB (serve gzipped)")


if __name__ == '__main__':
    main()
